name: Build Cordova APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Build APK
        run: |
          cordova create catalogo-apk com.byZcode.catalogo CatalogoProductos
          cd catalogo-apk
          cordova platform add android
          cordova build android

